### ISSUE TITLE
Organize Folder Structure

### ISSUE THREAD

**Issue by omarzeroual** [omarzeroual/Lorem-Ipsum-Pizza#15]

**Comment by silvanbitterli** [comment]
auf dem server hat es nun die Verzeichnisse "html" und "php". Bevor ihr das nächste mal was auf den Server lädt, bitte das **bisherige file auf dem Server löschen, Dateiaufrufe im code anpassen und ins richtige Folder uploaden.**

**Comment by omarzeroual** [comment]
Bitte sicher gehen, das alle Verknüpfungen wieder stimmen!!! Sei es auf HTML, CSS, PHP
@silvanbitterli
