### ISSUE TITLE
Dokumentation nachführen für Tätigkeiten zw. 28.9.-05.10.

### ISSUE THREAD

**Issue by omarzeroual** [omarzeroual/Lorem-Ipsum-Pizza#55]

**Comment by omarzeroual** [comment]
Umsetzung Produktauswahl dokumentiert. Update von Speisekarte Umsetzung.

**Comment by silvanbitterli** [comment]
Umsetzung Bestellungsbestätigung dokumentiert und Reflexion erstellt.
